name: Translate

on:
  workflow_dispatch:
    inputs:
      fileId:
        description: 'File ID'
        required: false

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Translate
        run: |
          python src/caster.py \
            remote \
            --project ${{ secrets.PROJECT_ID }} \
            --token ${{ secrets.CROWDIN_TOKEN }} \
            --file ${{ github.event.inputs.fileId }}
